[features]
seeds = false
skip-lint = false
[programs.localnet]
mate = "2CNaUh5Kkefntj1D6xp6r1se5PmghdizNBu6dwthVnrw"
[programs.devnet]
mate = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "dev_account.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
